[versions]
jvmdowngrader = "1.3.5"
netty = "4.1.128.Final"
shadow = "9.2.2"
spotless = "8.1.0"
taterlib-lite = "0.2.0-SNAPSHOT"
unimined = "1.3.16-SNAPSHOT"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.2" }
asm-tree = { group = "org.ow2.asm", name = "asm-tree", version = "6.2" }
entrypoint-spoof = { group = "dev.neuralnexus", name = "entrypoint-spoof", version = "0.1.26" }
guava = { group = "com.google.guava", name = "guava", version = "33.3.1-jre" }
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.0" }
mixin = { group = "org.spongepowered", name = "mixin", version = "0.8.5-SNAPSHOT" }
mojang-authlib = { group = "com.mojang", name = "authlib", version = "7.0.61" }
mojang-brigadier = { group = "com.mojang", name = "brigadier", version = "1.0.18" }
netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-codec = { group = "io.netty", name = "netty-codec", version.ref = "netty" }
taterlib-lite-base = { group = "dev.neuralnexus.taterlib.lite", name = "base", version.ref = "taterlib-lite" }
taterlib-lite-core = { group = "dev.neuralnexus.taterlib.lite", name = "core", version.ref = "taterlib-lite" }
taterlib-lite-metadata = { group = "dev.neuralnexus.taterlib.lite", name = "metadata", version.ref = "taterlib-lite" }
taterlib-lite-muxins = { group = "dev.neuralnexus.taterlib.lite", name = "muxins", version.ref = "taterlib-lite" }

[plugins]
jvmdowngrader = { id = "xyz.wagyourtail.jvmdowngrader", version.ref = "jvmdowngrader" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
unimined = { id = "xyz.wagyourtail.unimined", version.ref = "unimined" }
