modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${license}"
issueTrackerURL = "${issue_tracker_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL = "${update_json_url}"
displayURL = "${homepage_url}"
logoFile = "${mod_name}.png"
credits = "${authors}"
authors = "${authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${description}'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "${mod_id}.mixins.json"

# NeoForge Dependency
[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = false
type="optional"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
